apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dotnet-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-component
    app.kubernetes.io/part-of: e2e-dotnet
  name: dotnet-component
  namespace: e2e-demo-opnz
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dotnet-component
    weight: 100
status: {}
